{% set name = "apache-airflow-providers-salesforce" %}
{% set version = "3.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-salesforce-{{ version }}.tar.gz
  sha256: 75bb870b9ae6ce3feef0986d7489725cba750fc99ba7df96194d184dc582540c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - pandas >=0.17.1,<2.0
    - simple-salesforce >=1.0.0
    - tableauserverclient

test:
  imports:
    - airflow.providers.salesforce
    - airflow.providers.salesforce.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Salesforce for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-salesforce/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
